plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.lectorpatentes'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.lectorpatentes"
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    aaptOptions {
        noCompress "tflite"
    }
}

dependencies {
    // Librerías base de Android (Versiones estables para SDK 33)
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Google ML Kit (Reconocimiento de texto)
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:19.0.0'

    // TensorFlow Lite (El cerebro de la IA)
    implementation 'org.tensorflow:tensorflow-lite:2.14.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
    implementation 'org.tensorflow:tensorflow-lite-task-vision:0.4.4'

}